select * from dataset_acidentes2;

CREATE TABLE "APP"."DATASET_ACIDENTES2" 
   (	"DATA" CHAR(10 BYTE), 
	"HORARIO" CHAR(8 BYTE), 
	"N_DA_OCORRENCIA" NUMBER(38,0), 
	"TIPO_DE_OCORRENCIA" VARCHAR2(50 BYTE), 
	"KM" NUMBER(38,8), 
	"TRECHO" VARCHAR2(50 BYTE), 
	"SENTIDO" VARCHAR2(50 BYTE), 
	"TIPO_DE_ACIDENTE" VARCHAR2(300 BYTE), 
	"AUTOMOVEL" NUMBER(38,0), 
	"BICICLETA" NUMBER(38,0), 
	"CAMINHAO" NUMBER(38,0), 
	"MOTO" NUMBER(38,0), 
	"ONIBUS" NUMBER(38,0), 
	"OUTROS" NUMBER(38,0), 
	"TRACAO_ANIMAL" NUMBER(26,0), 
	"TRANSPORTE_DE_CARGAS_ESPECIAIS" NUMBER(26,0), 
	"TRATOR_MAQUINAS" NUMBER(26,0), 
	"UTILITARIOS" NUMBER(38,0), 
	"ILESOS" NUMBER(38,0), 
	"LEVEMENTE_FERIDOS" NUMBER(38,0), 
	"MODERADAMENTE_FERIDOS" NUMBER(38,0), 
	"GRAVEMENTE_FERIDOS" NUMBER(38,0), 
	"MORTOS" NUMBER(38,0),
    "ID" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

