UPDATE DATASET_ACIDENTES SET TIPO_DE_OCORRENCIA = 
(SELECT TDO_ID FROM TIPO_DE_OCORRENCIA 
WHERE tipo_de_ocorrencia.tdo_descricao = DATASET_ACIDENTES.TIPO_DE_OCORRENCIA);

UPDATE DATASET_ACIDENTES SET TIPO_DE_ACIDENTE = 
(SELECT TDA_ID FROM TIPO_DE_ACIDENTE 
WHERE TIPO_DE_ACIDENTE.tda_descricao = DATASET_ACIDENTES.tipo_de_acidente);

UPDATE DATASET_ACIDENTES SET TRECHO = 
(SELECT TRC_ID FROM TRECHO 
WHERE TRECHO.TRC_descricao = DATASET_ACIDENTES.TRECHO);

UPDATE DATASET_ACIDENTES SET KM = 
(SELECT LCL_ID FROM LOCAL 
WHERE LOCAL.LCL_KM = DATASET_ACIDENTES.KM);

SELECT * FROM LOCAL WHERE LCL_ID = 2704;

UPDATE DATASET_ACIDENTES SET SENTIDO = 
(SELECT SNT_ID FROM SENTIDO 
WHERE SENTIDO.SNT_DESCRICAO = DATASET_ACIDENTES.SENTIDO);

SELECT COUNT(*) FROM DATASET_ACIDENTES WHERE TIPO_DE_ACIDENTE IS NULL;

DELETE FROM DATASET_ACIDENTES WHERE TIPO_DE_ACIDENTE IS NULL;



