--------------------------------------------------------
--  Arquivo criado - sexta-feira-novembro-03-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_AUD
--------------------------------------------------------

   CREATE SEQUENCE  "AUDITOR"."SEQ_AUD"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 66 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table AUDITA_HISTORICOS
--------------------------------------------------------

  CREATE TABLE "AUDITOR"."AUDITA_HISTORICOS" 
   (	"AUD_ID" NUMBER(*,0), 
	"AUD_TABELA" VARCHAR2(30 BYTE), 
	"AUD_EVENTO" CHAR(1 BYTE), 
	"AUD_COLUNA" VARCHAR2(30 BYTE), 
	"AUD_VALOR_ANTIGO" VARCHAR2(200 BYTE), 
	"AUD_VALOR_NOVO" VARCHAR2(200 BYTE), 
	"AUD_ID_HIST_1" NUMBER(*,0), 
	"AUD_ID_HIST_2" NUMBER(*,0), 
	"AUD_DT_HIST" DATE, 
	"AUD_BD_USER" VARCHAR2(30 BYTE), 
	"AUD_SO_USER" VARCHAR2(255 BYTE), 
	"AUD_IP" CHAR(15 BYTE), 
	"AUD_MAC" VARCHAR2(100 BYTE), 
	"AUD_DT_AUDITORIA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into AUDITOR.AUDITA_HISTORICOS
SET DEFINE OFF;
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('1','HVEICULOS','U','HVEI_TIPO','automovel','AUTO MOVEL','1',null,to_date('25/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('25/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('2','HVEICULOS','U','HVEI_TIPO','AUTO MOVEL','AUTO MOVEL 2','1',null,to_date('25/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('25/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('3','HVEICULOS','D','HVEI_ID','1',null,'1',null,to_date('25/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('25/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('4','HVEICULOS','D','HVEI_TIPO','AUTO MOVEL 2',null,'1',null,to_date('25/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('25/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('5','HVEICULOS','D','HVEI_DT_ENTRADA','25/10/23',null,'1',null,to_date('25/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('25/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('6','HVEICULOS','U','HVEI_TIPO','AUTO MOVEL','AUTO MOVEL 2','1',null,to_date('25/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('25/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('7','HGRAVIDADE','U','HGRV_DESCRICAO','ilesos','ILESOS','1',null,to_date('26/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('26/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('8','HGRAVIDADE','D','HGRV_ID','1',null,'1',null,to_date('26/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('26/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('9','HGRAVIDADE','D','HGRV_DESCRICAO','ILESOS',null,'1',null,to_date('26/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('26/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('10','HGRAVIDADE','D','HGRV_DT_ENTRADA','26/10/23',null,'1',null,to_date('26/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('26/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('11','HTIPO_DE_ACIDENTE','U','HTDA_DESCRICAO','Acidentes de outra natureza','Acidentes de outra natureza 123','151',null,to_date('26/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('26/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('12','HTIPO_DE_ACIDENTE','D','HTDA_ID','151',null,'151',null,to_date('26/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('26/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('13','HTIPO_DE_ACIDENTE','D','HTDA_DESCRICAO','Acidentes de outra natureza 123',null,'151',null,to_date('26/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('26/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('14','HTIPO_DE_ACIDENTE','D','HTDA_DT_ENTRADA','26/10/23',null,'151',null,to_date('26/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('26/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('15','HLOCAL','U','HLCL_KM','70,6','70','1580',null,to_date('26/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('26/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('16','HLOCAL','D','HLCL_ID','1580',null,'1580',null,to_date('26/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('26/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('17','HLOCAL','D','HLCL_KM','70',null,'1580',null,to_date('26/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('26/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('18','HLOCAL','D','HLCL_DT_ENTRADA','26/10/23',null,'1580',null,to_date('26/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('26/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('19','HSENTIDO','U','HSNT_DESCRICAO','Crescente','cRESCENTE','1',null,to_date('27/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('20','HSENTIDO','D','HSNT_ID','1',null,'1',null,to_date('27/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('21','HSENTIDO','D','HSNT_DESCRICAO','cRESCENTE',null,'1',null,to_date('27/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('22','HSENTIDO','D','HSNT_DT_ENTRADA','27/10/23',null,'1',null,to_date('27/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('23','HGRAVIDADE_OCORRENCIAS','U','HGOC_QTDE_VITIMAS','1','10','1','108377',to_date('03/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('24','HGRAVIDADE_OCORRENCIAS','U','HGOC_QTDE_VITIMAS','2','10','1','108377',to_date('27/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('25','HGRAVIDADE_OCORRENCIAS','D','HGOC_GRV_ID','1',null,'1','108377',to_date('03/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('26','HGRAVIDADE_OCORRENCIAS','D','HGOC_OCR_ID','108377',null,'1','108377',to_date('03/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('27','HGRAVIDADE_OCORRENCIAS','D','HGOC_QTDE_VITIMAS','10',null,'1','108377',to_date('03/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('28','HGRAVIDADE_OCORRENCIAS','D','HGOC_DT_ENTRADA','03/10/23',null,'1','108377',to_date('03/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('29','HGRAVIDADE_OCORRENCIAS','D','HGOC_GRV_ID','1',null,'1','108377',to_date('27/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('30','HGRAVIDADE_OCORRENCIAS','D','HGOC_OCR_ID','108377',null,'1','108377',to_date('27/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('31','HGRAVIDADE_OCORRENCIAS','D','HGOC_QTDE_VITIMAS','10',null,'1','108377',to_date('27/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('32','HGRAVIDADE_OCORRENCIAS','D','HGOC_DT_ENTRADA','27/10/23',null,'1','108377',to_date('27/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('33','HTIPO_DE_OCORRENCIA','U','HTDO_DESCRICAO','com danos materiais','COM DANOS MORAIS','7',null,to_date('27/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('34','HTIPO_DE_OCORRENCIA','D','HTDO_ID','7',null,'7',null,to_date('27/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('35','HTIPO_DE_OCORRENCIA','D','HTDO_DESCRICAO','COM DANOS MORAIS',null,'7',null,to_date('27/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('36','HTIPO_DE_OCORRENCIA','D','HTDO_DT_ENTRADA','27/10/23',null,'7',null,to_date('27/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('37','HVEICULOS_OCORRENCIAS','U','HVOC_QTDE_VEICULOS','1','11','130632','11',to_date('27/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('38','HVEICULOS_OCORRENCIAS','D','HVOC_OCR_ID','130632',null,'130632','11',to_date('27/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('39','HVEICULOS_OCORRENCIAS','D','HVOC_VEI_ID','11',null,'130632','11',to_date('27/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('40','HVEICULOS_OCORRENCIAS','D','HVOC_QTDE_VEICULOS','11',null,'130632','11',to_date('27/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('41','HVEICULOS_OCORRENCIAS','D','HVOC_DT_ENTRADA','27/10/23',null,'130632','11',to_date('27/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('42','HTRECHO','U','HTRC_DESCRICAO','BR-381/MG','BR','1',null,to_date('27/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('43','HTRECHO','D','HTRC_ID','1',null,'1',null,to_date('27/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('44','HTRECHO','D','HTRC_DESCRICAO','BR',null,'1',null,to_date('27/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('45','HTRECHO','D','HTRC_DT_ENTRADA','27/10/23',null,'1',null,to_date('27/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('46','HOCORRENCIAS','U','HOCR_NR_OCORRENCIA','81','777','108608',null,to_date('03/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('47','HOCORRENCIAS','U','HOCR_NR_OCORRENCIA','1823','777','108608',null,to_date('27/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('48','HOCORRENCIAS','D','HOCR_ID','108608',null,'108608',null,to_date('03/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('49','HOCORRENCIAS','D','HOCR_DATA_HORA','22/09/20',null,'108608',null,to_date('03/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('50','HOCORRENCIAS','D','HOCR_NR_OCORRENCIA','777',null,'108608',null,to_date('03/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('51','HOCORRENCIAS','D','HOCR_LCL_ID','10609',null,'108608',null,to_date('03/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('52','HOCORRENCIAS','D','HOCR_TDO_ID','7',null,'108608',null,to_date('03/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('53','HOCORRENCIAS','D','HOCR_TDA_ID','169',null,'108608',null,to_date('03/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('54','HOCORRENCIAS','D','HOCR_SNT_ID','3',null,'108608',null,to_date('03/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('55','HOCORRENCIAS','D','HOCR_TRC_ID','1',null,'108608',null,to_date('03/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('56','HOCORRENCIAS','D','HOCR_DT_ENTRADA','03/10/23',null,'108608',null,to_date('03/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('57','HOCORRENCIAS','D','HOCR_ID','108608',null,'108608',null,to_date('27/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('58','HOCORRENCIAS','D','HOCR_DATA_HORA','22/09/20',null,'108608',null,to_date('27/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('59','HOCORRENCIAS','D','HOCR_NR_OCORRENCIA','777',null,'108608',null,to_date('27/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('60','HOCORRENCIAS','D','HOCR_LCL_ID','10609',null,'108608',null,to_date('27/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('61','HOCORRENCIAS','D','HOCR_TDO_ID','7',null,'108608',null,to_date('27/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('62','HOCORRENCIAS','D','HOCR_TDA_ID','169',null,'108608',null,to_date('27/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('63','HOCORRENCIAS','D','HOCR_SNT_ID','3',null,'108608',null,to_date('27/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('64','HOCORRENCIAS','D','HOCR_TRC_ID','1',null,'108608',null,to_date('27/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
Insert into AUDITOR.AUDITA_HISTORICOS (AUD_ID,AUD_TABELA,AUD_EVENTO,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_ID_HIST_1,AUD_ID_HIST_2,AUD_DT_HIST,AUD_BD_USER,AUD_SO_USER,AUD_IP,AUD_MAC,AUD_DT_AUDITORIA) values ('65','HOCORRENCIAS','D','HOCR_DT_ENTRADA','27/10/23',null,'108608',null,to_date('27/10/23','DD/MM/RR'),'APP','vitto','127.0.0.1      ','unknown',to_date('27/10/23','DD/MM/RR'));
--------------------------------------------------------
--  DDL for Trigger TG_SEQ_AUD
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "AUDITOR"."TG_SEQ_AUD" 
BEFORE INSERT ON AUDITA_HISTORICOS
FOR EACH ROW
BEGIN 
       :NEW.AUD_ID := SEQ_AUD.NEXTVAL;
END;
/
ALTER TRIGGER "AUDITOR"."TG_SEQ_AUD" ENABLE;
--------------------------------------------------------
--  DDL for Procedure PRC_INS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "AUDITOR"."PRC_INS" 
(
    P_TABELA IN VARCHAR2,
    P_EVENTO IN VARCHAR2,
    P_COLUNA IN VARCHAR2,
    P_ANTIGO IN VARCHAR2,
    P_NOVO IN VARCHAR2,
    P_ID_H1 IN NUMBER,
    P_ID_H2 IN NUMBER,
    P_DT_H IN DATE,
    P_USU_BD IN VARCHAR2,
    P_USU_SO IN VARCHAR2,
    P_IP IN VARCHAR2,
    P_MAC IN VARCHAR2
) AS
BEGIN INSERT INTO AUDITA_HISTORICOS VALUES(
            0, 
            P_TABELA,
            P_EVENTO,
            P_COLUNA,
            P_ANTIGO,
            P_NOVO,
            P_ID_H1,
            P_ID_H2,
            P_DT_H,
            P_USU_BD,
            P_USU_SO,
            P_IP,
            P_MAC,
            SYSDATE
            );END PRC_INS;

/

  GRANT EXECUTE ON "AUDITOR"."PRC_INS" TO "APP";
