create or replace NONEDITIONABLE TRIGGER TG_INS_HVEI
BEFORE DELETE OR UPDATE ON HVEICULOS
FOR EACH ROW
DECLARE
V_TABELA VARCHAR (30) := 'HVEICULOS';
V_USU_BD VARCHAR(30);
V_USU_SO VARCHAR(255) := SYS_CONTEXT ('USERENV','OS_USER');
V_IP CHAR(15) := SYS_CONTEXT ('USERENV','IP_ADDRESS');
V_MAC varchar(100) := SYS_CONTEXT ('USERENV', 'TERMINAL');
BEGIN
SELECT USER INTO V_USU_BD FROM DUAL;
IF DELETING THEN
AUDITOR.PRC_INS(V_TABELA, 'D','HVEI_ID',:OLD.HVEI_ID, NULL, :OLD.HVEI_ID, NULL, :OLD.HVEI_DT_ENTRADA, v_usu_bd, v_usu_so, v_ip, v_mac);
AUDITOR.PRC_INS(V_TABELA, 'D','HVEI_TIPO', :OLD.HVEI_TIPO, NULL, :OLD.HVEI_ID, NULL, :OLD.HVEI_DT_ENTRADA,v_usu_bd, v_usu_so, v_ip, v_mac);
AUDITOR.PRC_INS(V_TABELA, 'D','HVEI_DT_ENTRADA',:OLD.HVEI_DT_ENTRADA, NULL, :OLD.HVEI_ID, NULL, :OLD.HVEI_DT_ENTRADA,v_usu_bd ,v_usu_so, v_ip, v_mac);
END IF;

IF UPDATING THEN
    IF(:OLD.HVEI_ID <> :NEW.HVEI_ID) THEN
       AUDITOR.PRC_INS (V_TABELA, 'U','HVEI_ID',:OLD.HVEI_ID, :NEW.HVEI_ID, :OLD.HVEI_ID,NULL, :OLD.HVEI_DT_ENTRADA,v_usu_bd,v_usu_so,v_ip,v_mac);
END IF;
    IF(:OLD.HVEI_TIPO <> :NEW.HVEI_TIPO) THEN
       AUDITOR.PRC_INS (V_TABELA, 'U','HVEI_TIPO',:OLD.HVEI_TIPO, :NEW.HVEI_TIPO, :OLD.HVEI_ID, NULL, :OLD.HVEI_DT_ENTRADA,v_usu_bd,v_usu_so,v_ip,v_mac);
END IF;
     IF(:OLD.HVEI_DT_ENTRADA <> :NEW.HVEI_DT_ENTRADA) THEN
       AUDITOR.PRC_INS (V_TABELA, 'U','HVEI_DT_ENTRADA',:OLD.HVEI_DT_ENTRADA, :NEW.HVEI_DT_ENTRADA, :OLD.HVEI_ID, NULL, :OLD.HVEI_DT_ENTRADA,v_usu_bd,v_usu_so,v_ip,v_mac);
END IF;
END IF;
END;


