CREATE TABLE AUDITA_HISTORICOS(
    AUD_ID INTEGER,
    AUD_TABELA VARCHAR(30),
    AUD_EVENTO CHAR(1),
    AUD_COLUNA VARCHAR(30),
    AUD_VALOR_ANTIGO VARCHAR(200),
    AUD_VALOR_NOVO VARCHAR(200),
    AUD_ID_HIST_1 INTEGER,
    AUD_ID_HIST_2 INTEGER,
    AUD_DT_HIST DATE,
    AUD_BD_USER VARCHAR(30),
    AUD_SO_USER VARCHAR(255),
    AUD_IP CHAR(15),
    AUD_MAC VARCHAR(100),
    AUD_DT_AUDITORIA DATE
)

CREATE SEQUENCE SEQ_AUD NOCACHE;

CREATE TRIGGER TG_SEQ_AUD
BEFORE INSERT ON AUDITA_HISTORICOS
FOR EACH ROW
BEGIN 
       :NEW.AUD_ID := SEQ_AUD.NEXTVAL;
END;


GRANT EXECUTE ON PRC_INS TO APP;