DELETE FROM OCORRENCIAS;

DELETE FROM VEICULOS_OCORRENCIAS;

INSERT INTO OCORRENCIAS 
SELECT 
ID,
DATA_HORA,
N_DA_OCORRENCIA,
KM,
TIPO_DE_OCORRENCIA,
TIPO_DE_ACIDENTE,
SENTIDO,
TRECHO
FROM DATASET_ACIDENTES3 WHERE EXTRACT(YEAR FROM DATA_HORA) > 2019 AND EXTRACT(YEAR FROM DATA_HORA) < 2021;

SELECT * FROM OCORRENCIAS ORDER BY OCR_ID;

SELECT * FROM VEICULOS_OCORRENCIAS;

SELECT COUNT(*) FROM VEICULOS_OCORRENCIAS;

SELECT COUNT(*) FROM DATASET_ACIDENTES3 where TRATOR_MAQUINAS != 0 AND EXTRACT(YEAR FROM DATA_HORA) > 2019 AND EXTRACT(YEAR FROM DATA_HORA) < 2021



SELECT 
ID,
DATA_HORA,
N_DA_OCORRENCIA,
KM,
TIPO_DE_OCORRENCIA,
TIPO_DE_ACIDENTE,
SENTIDO,
TRECHO
FROM DATASET_ACIDENTES3 WHERE EXTRACT(YEAR FROM DATA_HORA) > 2019 AND EXTRACT(YEAR FROM DATA_HORA) < 2021;

SELECT COUNT(*) from dataset_acidentes3 where UTILITARIOS != 0 AND EXTRACT(YEAR FROM DATA_HORA) > 2019 AND EXTRACT(YEAR FROM DATA_HORA) < 2021;

select count(*) from veiculos_ocorrencias where voc_vei_id = 11;

