SELECT TDA_DESCRICAO, COUNT(*) 
FROM SELECT TDA_DESCRICAO, COUNT(*) 
FROM TIPO_DE_ACIDENTE
GROUP BY TDA_DESCRICAO
HAVING COUNT(*) > 1;
GROUP BY TDA_DESCRICAO
HAVING COUNT(*) > 1;

DELETE FROM TIPO_DE_ACIDENTE WHERE TDA_ID = 180;

SELECT DISTINCT data || ' ' || horario FROM DATASET_ACIDENTES ORDER BY 1;

SELECT COUNT(*) FROM DATASET_ACIDENTES WHERE HORARIO IS NULL;

SELECT DISTINCT
    0,
    --TO_DATE(data || ' ' || horario,'DD/MM/YYYY HH24:MI:SS'),
    data || ' ' || horario,
    n_da_ocorrencia,
    km,
    trecho,
    sentido,
    tipo_de_acidente
    SENTIDO,
    TRECHO
FROM
    dataset_acidentes;
    
    DELETE FROM DATASET_ACIDENTES WHERE DATA IS NULL;
    
    SELECT COUNT(*) FROM DATASET_ACIDENTES;
    
INSERT INTO OCORRENCIAS 
SELECT DISTINCT 
0,
TO_DATE(data || ' ' || horario,'DD/MM/YYYY HH24:MI:SS'),
N_DA_OCORRENCIA,
to_number(KM),
to_number(TIPO_DE_OCORRENCIA),
to_number(TIPO_DE_ACIDENTE),
to_number(SENTIDO),
to_number(TRECHO)
FROM DATASET_ACIDENTES;

SELECT * FROM TIPO_DE_ACIDENTE;


SELECT COUNT(*) FROM DATASET_ACIDENTES WHERE KM IS NULL;
SELECT COUNT(*) FROM DATASET_ACIDENTES WHERE N_DA_OCORRENCIA IS NULL;
SELECT COUNT(*) FROM DATASET_ACIDENTES WHERE TIPO_DE_OCORRENCIA IS NULL;



DELETE FROM DATASET_ACIDENTES WHERE SENTIDO IS NULL;

SELECT * FROM DATASET_ACIDENTES WHERE TIPO_DE_ACIDENTE = 180;

SELECT TDA_ID, DATA, HORARIO FROM DATASET_ACIDENTES LEFT JOIN TIPO_DE_ACIDENTE ON TIPO_DE_ACIDENTE.TDA_ID = DATASET_ACIDENTES.TIPO_DE_ACIDENTE;

DELETE FROM DATASET_ACIDENTES WHERE DATA < '01/01/2020';

SELECT COUNT(*) FROM DATASET_ACIDENTES;


SELECT TDA_ID, DATA, HORARIO FROM DATASET_ACIDENTES LEFT JOIN TIPO_DE_ACIDENTE ON TIPO_DE_ACIDENTE.TDA_ID = DATASET_ACIDENTES.TIPO_DE_ACIDENTE WHERE TDA_ID != TIPO_DE_ACIDENTE;

SELECT TDA_ID FROM TIPO_DE_ACIDENTE;

SELECT DISTINCT TIPO_DE_ACIDENTE FROM DATASET_ACIDENTES ORDER BY TIPO_DE_ACIDENTE;

SELECT * FROM DATASET_ACIDENTES WHERE TIPO_DE_ACIDENTE LIKE '%u%';
