-- carga 2

INSERT INTO OCORRENCIAS
SELECT DISTINCT 
ID,
DATA_HORA,
N_DA_OCORRENCIA,
KM,
TIPO_DE_OCORRENCIA,
TIPO_DE_ACIDENTE,
SENTIDO,
TRECHO
FROM DATASET_ACIDENTES3
WHERE DATA_HORA > TO_DATE('2020-12-31', 'YYYY-MM-DD')


SELECT * FROM OCORRENCIAS ORDER BY OCR_ID DESC

SELECT COUNT(*) FROM OCORRENCIAS

SELECT  * FROM OCORRENCIAS where OCR_DATA_HORA > TO_DATE('2020-12-31', 'YYYY-MM-DD')

SELECT * FROM DATASET_ACIDENTES3 where DATA_HORA = TO_DATE('2020-12-31', 'YYYY-MM-DD')

SELECT * FROM VEICULOS_OCORRENCIAS INNER JOIN OCORRENCIAS ON VOC_OCR_ID = OCR_ID where OCR_DATA_HORA > TO_DATE('2020-12-31', 'YYYY-MM-DD') AND VOC_VEI_ID = 2;


SELECT * FROM VEICULOS_OCORRENCIAS INNER JOIN OCORRENCIAS ON VOC_OCR_ID = OCR_ID WHERE VOC_VEI_ID = 3 ORDER BY OCR_DATA_HORA DESC;

SELECT DISTINCT COUNT(*) FROM VEICULOS_OCORRENCIAS INNER JOIN OCORRENCIAS ON VOC_OCR_ID = OCR_ID WHERE VOC_VEI_ID = 3 ORDER BY OCR_DATA_HORA DESC;

SELECT COUNT(*) FROM VEICULOS_OCORRENCIAS INNER JOIN OCORRENCIAS ON VOC_OCR_ID = OCR_ID WHERE VOC_VEI_ID = 3 ORDER BY OCR_DATA_HORA DESC;

SELECT DISTINCT id, TRANSPORTE_DE_CARGAS_ESPECIAIS from dataset_acidentes3 where TRANSPORTE_DE_CARGAS_ESPECIAIS != 0 AND TRANSPORTE_DE_CARGAS_ESPECIAIS IS NOT NULL AND DATA_HORA > TO_DATE('2020-12-31', 'YYYY-MM-DD')


SELECT DISTINCT id, TRACAO_ANIMAL from dataset_acidentes3 where TRACAO_ANIMAL != 0 AND TRACAO_ANIMAL IS NOT NULL AND DATA_HORA > TO_DATE('2020-12-31', 'YYYY-MM-DD')

SELECT DISTINCT id, TRATOR_MAQUINAS from dataset_acidentes3 where TRATOR_MAQUINAS != 0 AND TRATOR_MAQUINAS IS NOT NULL AND DATA_HORA > TO_DATE('2020-12-31', 'YYYY-MM-DD')

SELECT DISTINCT id, UTILITARIOS from dataset_acidentes3 where UTILITARIOS != 0 AND UTILITARIOS IS NOT NULL AND DATA_HORA > TO_DATE('2020-12-31', 'YYYY-MM-DD')

SELECT DISTINCT id, LEVEMENTE_FERIDOS from dataset_acidentes3 where LEVEMENTE_FERIDOS != 0 AND LEVEMENTE_FERIDOS IS NOT NULL AND DATA_HORA > TO_DATE('2020-12-31', 'YYYY-MM-DD')

SELECT DISTINCT id, GRAVEMENTE_FERIDOS from dataset_acidentes3 where GRAVEMENTE_FERIDOS != 0 AND GRAVEMENTE_FERIDOS IS NOT NULL AND DATA_HORA > TO_DATE('2020-12-31', 'YYYY-MM-DD')

SELECT EXTRACT(YEAR FROM OCR_DATA_HORA) AS ANO,
       COUNT(*) AS TOTAL_OCORRENCIAS
  FROM APP.OCORRENCIAS
GROUP BY EXTRACT(YEAR FROM OCR_DATA_HORA)
HAVING EXTRACT(YEAR FROM OCR_DATA_HORA) IN (2020, 2021, 2022, 2023)
ORDER BY ANO;
