--ISAC 

create or replace NONEDITIONABLE TRIGGER TG_INS_HGRV
BEFORE DELETE OR UPDATE ON HGRAVIDADE
FOR EACH ROW
DECLARE
V_TABELA VARCHAR (30) := 'HGRAVIDADE';
V_USU_BD VARCHAR(30);
V_USU_SO VARCHAR(255) := SYS_CONTEXT ('USERENV','OS_USER');
V_IP CHAR(15) := SYS_CONTEXT ('USERENV','IP_ADDRESS');
V_MAC varchar(100) := SYS_CONTEXT ('USERENV', 'TERMINAL');
BEGIN
SELECT USER INTO V_USU_BD FROM DUAL;
IF DELETING THEN
auditor.PRC_INS(V_TABELA, 'D','HGRV_ID',:OLD.HGRV_ID, NULL, :OLD.HGRV_ID, NULL, :OLD.HGRV_DT_ENTRADA, v_usu_bd, v_usu_so, v_ip, v_mac);
auditor.PRC_INS(V_TABELA, 'D','HGRV_DESCRICAO', :OLD.HGRV_DESCRICAO, NULL, :OLD.HGRV_ID, NULL, :OLD.HGRV_DT_ENTRADA, v_usu_bd, v_usu_so, v_ip, v_mac);
auditor.PRC_INS(V_TABELA, 'D','HGRV_DT_ENTRADA',:OLD.HGRV_DT_ENTRADA, NULL, :OLD.HGRV_ID, NULL, :OLD.HGRV_DT_ENTRADA,v_usu_bd ,v_usu_so, v_ip, v_mac);
END IF; 

IF UPDATING THEN
    IF(:OLD.HGRV_ID <> :NEW.HGRV_ID) THEN
       auditor.PRC_INS (V_TABELA, 'U','HGRV_ID',:OLD.HGRV_ID, :NEW.HGRV_ID, :OLD.HGRV_ID,NULL, :OLD.HGRV_DT_ENTRADA,v_usu_bd,v_usu_so,v_ip,v_mac);
END IF;
    IF(:OLD.HGRV_DESCRICAO <> :NEW.HGRV_DESCRICAO) THEN
       AUDITOR.PRC_INS (V_TABELA, 'U','HGRV_DESCRICAO',:OLD.HGRV_DESCRICAO, :NEW.HGRV_DESCRICAO, :OLD.HGRV_ID, NULL, :OLD.HGRV_DT_ENTRADA,v_usu_bd,v_usu_so,v_ip,v_mac);
END IF;
     IF(:OLD.HGRV_DT_ENTRADA <> :NEW.HGRV_DT_ENTRADA) THEN
       AUDITOR.PRC_INS (V_TABELA, 'U','HGRV_DT_ENTRADA',:OLD.HGRV_DT_ENTRADA, :NEW.HGRV_DT_ENTRADA, :OLD.HGRV_ID, NULL, :OLD.HGRV_DT_ENTRADA,v_usu_bd,v_usu_so,v_ip,v_mac);
END IF;
END IF;
END;

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

create or replace NONEDITIONABLE TRIGGER TG_INS_HTDA
BEFORE DELETE OR UPDATE ON HTIPO_DE_ACIDENTE
FOR EACH ROW
DECLARE
V_TABELA VARCHAR (30) := 'HTIPO_DE_ACIDENTE';
V_USU_BD VARCHAR(30);
V_USU_SO VARCHAR(255) := SYS_CONTEXT ('USERENV','OS_USER');
V_IP CHAR(15) := SYS_CONTEXT ('USERENV','IP_ADDRESS');
V_MAC varchar(100) := SYS_CONTEXT ('USERENV', 'TERMINAL');
BEGIN
SELECT USER INTO V_USU_BD FROM DUAL;
IF DELETING THEN
auditor.PRC_INS(V_TABELA, 'D','HTDA_ID',:OLD.HTDA_ID, NULL, :OLD.HTDA_ID, NULL, :OLD.HTDA_DT_ENTRADA, v_usu_bd, v_usu_so, v_ip, v_mac);
auditor.PRC_INS(V_TABELA, 'D','HTDA_DESCRICAO', :OLD.HTDA_DESCRICAO, NULL, :OLD.HTDA_ID, NULL, :OLD.HTDA_DT_ENTRADA, v_usu_bd, v_usu_so, v_ip, v_mac);
auditor.PRC_INS(V_TABELA, 'D','HTDA_DT_ENTRADA',:OLD.HTDA_DT_ENTRADA, NULL, :OLD.HTDA_ID, NULL, :OLD.HTDA_DT_ENTRADA,v_usu_bd ,v_usu_so, v_ip, v_mac);
END IF; 

IF UPDATING THEN
    IF(:OLD.HTDA_ID <> :NEW.HTDA_ID) THEN
       auditor.PRC_INS (V_TABELA, 'U','HTDA_ID',:OLD.HTDA_ID, :NEW.HTDA_ID, :OLD.HTDA_ID,NULL, :OLD.HTDA_DT_ENTRADA,v_usu_bd,v_usu_so,v_ip,v_mac);
END IF;
    IF(:OLD.HTDA_DESCRICAO <> :NEW.HTDA_DESCRICAO) THEN
       AUDITOR.PRC_INS (V_TABELA, 'U','HTDA_DESCRICAO',:OLD.HTDA_DESCRICAO, :NEW.HTDA_DESCRICAO, :OLD.HTDA_ID, NULL, :OLD.HTDA_DT_ENTRADA,v_usu_bd,v_usu_so,v_ip,v_mac);
END IF;
     IF(:OLD.HTDA_DT_ENTRADA <> :NEW.HTDA_DT_ENTRADA) THEN
       AUDITOR.PRC_INS (V_TABELA, 'U','HTDA_DT_ENTRADA',:OLD.HTDA_DT_ENTRADA, :NEW.HTDA_DT_ENTRADA, :OLD.HTDA_ID, NULL, :OLD.HTDA_DT_ENTRADA,v_usu_bd,v_usu_so,v_ip,v_mac);
END IF;
END IF;
END;
